name: Build
on: [push, pull_request]

jobs:
  macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        run: |
          curl https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg --output pythonInstaller.pkg
          sudo installer -pkg pythonInstaller.pkg -target /
      - name: Check Python install
        run: |
          which python3
          python3 --version
          which pip3
          pip3 --version
          python3 -m venv .
          . bin/activate
          pip3 install -U setuptools wheel pip pyinstaller
          pip3 install twisted[tls] appnope requests certifi
          pip3 install -r requirements.txt  
          pyinstaller SESMG.spec
      - name: Prepare for deployment
        run: |
          ls -al
          export VER="0.5.0"
          echo "VER=$VER" >> $GITHUB_ENV
          cd dist
          ls
          cd ..
          mkdir dist_actions
          . ci/macos-deploy.sh
          ls -al dist_actions
          
      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: SESMG_${{ env.VER }}.dmg
          path: |
            dist_actions/SESMG_${{ env.VER }}.dmg

 
