name: Semantic Release

on:
  push:
    branches:
      - master
      - test
      
permissions: 
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: get current version 
        run: |
          current_release=$(python setup.py --version)
          echo "current_release=v$current_release" >> $GITHUB_ENV

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: Build for macOS
    runs-on: macos-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get current version 
        run : |
          version=$(python setup.py --version)
          echo "version=v$version" >> $GITHUB_ENV
          
      - name: Setup Python
        if: ${{ env.current_release != env.version }}
        run: |
          curl https://www.python.org/ftp/python/3.9.13/python-3.9.13-macosx10.9.pkg --output pythonInstaller.pkg
          sudo installer -pkg pythonInstaller.pkg -target /
      - name: Create Executable
        if: ${{ env.current_release != env.version }}
        run: |
          python3 -m venv .
          . bin/activate
          pip3 install -U setuptools wheel pip pyinstaller
          pip3 install twisted[tls] appnope requests certifi
          pip3 install -r requirements.txt  
          pyinstaller .github/deploy/SESMG_macos.spec
      - name: Prepare for deployment
        if: ${{ env.current_release != env.version }}
        run: |
          brew install create-dmg
          mkdir -p dist/dmg
          cp -r "dist/SESMG.app" dist/dmg
          create-dmg \
          --volname "SESMG" \
          --hide-extension "SESMG.app" \
          "dist/SESMG.dmg" \
          "dist/dmg/"
      - name: Upload Artifact
        if: ${{ env.current_release != env.version }}
        uses: actions/upload-artifact@v3
        with:
          name: SESMG.dmg
          path: dist/SESMG.dmg
          
  linux:
    name: Build on linux
    runs-on: ubuntu-20.04
    needs: [release, macos]
    steps:
      - name: Checkout
        if: ${{ env.current_release != env.version }}
        uses: actions/checkout@v2

      - name: Setup Python
        if: ${{ env.current_release != env.version }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Create Executable
        if: ${{ env.current_release != env.version }}
        run: |
          pip3 install virtualenv
          python3 -m virtualenv .
          . bin/activate
          sudo apt-get update 
          sudo apt-get install libc6
          pip3 install --upgrade setuptools
          pip3 install pyinstaller
          pip3 install twisted[tls] appnope requests certifi
          pip3 install -r requirements.txt  
          pyinstaller .github/deploy/SESMG_linux.spec
      - name: Prepare for deployment
        if: ${{ env.current_release != env.version }}
        run: |
          sudo apt-get install ruby-dev build-essential && sudo gem i fpm -f
          mkdir -p package/opt
          mkdir -p package/usr/share/applications
          mkdir -p package/usr/share/icons/hicolor/scalable/apps
          cp -r dist/SESMG package/opt/SESMG
          cp .github/deploy/SESMG.desktop package/usr/share/applications
          find package/opt/SESMG -type f -exec chmod 644 -- {} +
          find package/opt/SESMG -type d -exec chmod 755 -- {} +
          find package/usr/share -type f -exec chmod 644 -- {} +
          chmod +x package/opt/SESMG/SESMG
          fpm -C package -s dir -t deb -n "SESMG" -v 0.1.0 -p dist/SESMG.deb
      - name: Upload Artifact
        if: ${{ env.current_release != env.version }}
        uses: actions/upload-artifact@v3
        with:
          name: SESMG.deb
          path: dist/SESMG.deb
  
  windows:
      name: Build on windows
      runs-on: windows-latest
      needs: [release, macos, linux]
      steps:
        - name: Checkout
          if: ${{ env.current_release != env.version }}
          uses: actions/checkout@v2

        - name: Setup Python
          if: ${{ env.current_release != env.version }}
          uses: actions/setup-python@v4
          with:
            python-version: '3.9.13'
            
        - name: Add msbuild to PATH
          if: ${{ env.current_release != env.version }}
          uses: microsoft/setup-msbuild@v1.1

        - name: Create Executable
          if: ${{ env.current_release != env.version }}
          run: |
            python3 -m venv .
            Scripts/activate.bat
            Scripts/pip3 install --upgrade setuptools
            Scripts/pip3 install pyinstaller
            Scripts/pip3 install twisted[tls] appnope requests certifi
            Scripts/pip3 install -r requirements.txt  
            Scripts/pyinstaller .github/deploy/SESMG_windows.spec
            
        - name: Upload Artifact
          if: ${{ env.current_release != env.version }}
          uses: actions/upload-artifact@v2
          with:
            name: SESMG.exe
            path: |
              dist/SESMG.exe

            
  deploy:
    name: Push builds
    runs-on: ubuntu-20.04
    needs: [release, linux, macos, windows]
    steps:
      - name: Checkout
        if: ${{ env.current_release != env.version }}
        uses: actions/checkout@v2
      - name: Download MAC artifact
        if: ${{ env.current_release != env.version }}
        uses: actions/download-artifact@v3
        with:
          name: SESMG.dmg
      - name: Download LINUX artifact
        if: ${{ env.current_release != env.version }}
        uses: actions/download-artifact@v3
        with:
          name: SESMG.deb
      - name: Download WINDOWS artifact
        if: ${{ env.current_release != env.version }}
        uses: actions/download-artifact@v3
        with:
          name: SESMG.exe
      
      - name: GET VERSION 
        if: ${{ env.current_release != env.version }}
        run: |
          VERSION=$(python setup.py --version)
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Upload MAC binaries to release
        if: ${{ env.current_release != env.version }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./SESMG.dmg
          asset_name: SESMG.dmg
          tag: ${{ env.VERSION }}
          overwrite: true
      - name: Upload LINUX binaries to release
        if: ${{ env.current_release != env.version }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./SESMG.deb
          asset_name: SESMG.deb
          tag: ${{ env.VERSION }}
          overwrite: true
      - name: Upload WINDOWS binaries to release
        if: ${{ env.current_release != env.version }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./SESMG.exe
          asset_name: SESMG.exe
          tag: ${{ env.VERSION }}
          overwrite: true

 

